// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agnifryeckicjfabfgtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnbmlmcnllY2tpY2pmYWJmZ3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODgxODIsImV4cCI6MjA1NTY2NDE4Mn0.JwAXIgteH-utmSvCDI5wxnVxRHFpx7XfKLPnk6hY1XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);